{{- if .Values.clusterIssuer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-manager-webhook-volcengine.fullname" . }}-secret
  namespace: {{ .Values.certManager.namespace }}
  labels:
    app: {{ include "cert-manager-webhook-volcengine.name" . }}
    chart: {{ include "cert-manager-webhook-volcengine.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  accessKey: {{ required ".Values.clusterIssuer.accessKey is required" .Values.clusterIssuer.accessKey | b64enc | quote }}
  secretKey: {{ required ".Values.clusterIssuer.secretKey is required" .Values.clusterIssuer.secretKey | b64enc | quote }}
{{- end }}